import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "@user/_components";
import {
  SessionProvider,
  QueryProvider,
  ReduxProvider,
} from "@global/components/fragments";

import "@global/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SIMS PPOB - BEDY BRILIANT WIJAYA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ReduxProvider>
            <QueryProvider>
              <Header />
              {children}
            </QueryProvider>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
